version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapi
      - public-data:/webapi/public
      - tmp-data:/webapi/tmp
      - log-data:/webapi/log/*
    depends_on:
      - db
  db:
    image: postgres:12.1
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapi/public
      - tmp-data:/webapi/tmp
    ports:
      - 7777:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
