default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'root' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>
  host: db

development:
  <<: *default
  database: webapi_development

test:
  <<: *default
  database: webapi_test

production:
  <<: *default
  database: webapi_production
  username: webapi
  password: <%= ENV['WEBAPI_DATABASE_PASSWORD'] %>
